- name: OGS Monitoring
  hosts: all
  tasks:
    - name: Problem Detected Trying to recover !
      when: state == "OPEN"
      service:
        name: "{{ impactedEntity[31:] }}"
        state: restarted
