#!/bin/bash

# Get a list of unique process names
process_names=$(ps -e -o comm= | sort -u)

# Convert the list to JSON format for Zabbix LLD
json="{\"data\":["
first=true
while IFS= read -r process_name; do
    if [ "$first" = false ]; then
        json+=","
    fi
    json+="{\"{#PROCESSNAME}\":\"$process_name\"}"
    first=false
done <<< "$process_names"
json+="]}"

echo "$json"


top -b -n 1 | grep "Cpu(s)" -A1 | awk '/^%/ {print $2}' | sed -n '2p'
