- name: OGS Monitoring
  hosts: all
  tasks:
    - name: Problem Detected Trying to recover !
      become: {{ state }}
      service:
        name: "{{ impactedEntities.name }}"
        state: restarted
