- name: OGS Monitoring
  hosts: all
  tasks:
    - name: Problem Detected Trying to recover !
      when: state == "OPEN"
      service:
        name: "{{ impactedEntities.name }}"
        state: restarted
