- name: OGS Monitoring
  hosts: all
  tasks:
    - name: Open
      debug:
        msg: "Problem detected trying to recover!"
      when: state == "OPEN"
      service:
         name: "{{ impactedEntities.name }}"
         state: restarted
